version: "3.8"
services:
  twitch-viewer-bot:
    build: .
    container_name: twitch-viewer-bot
    environment:
      PROXY_CHOICE: 1         # Wähle den Proxy-Server aus
      TWITCH_USERNAME: kingrex_ttv # Twitch-Benutzername
      PROXY_COUNT: 50        # Anzahl der Proxies
    restart: unless-stopped
