version: "3.8"
services:
  twitch-viewer-bot:
    build: .
    container_name: twitch-viewer-bot
    environment:
      PROXY_CHOICE: 2         # Wähle den Proxy-Server aus
      TWITCH_USERNAME: default_username # Twitch-Benutzername
      PROXY_COUNT: 50        # Anzahl der Proxies
#      DEBUG: "true"         # Debug-Modus (true/false)
    restart: unless-stopped